# Generated by Django 5.2.17 on 2026-08-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'term'), name='unique_student_term_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='one_current_enrollment_per_student'),
        ),
    ]
