# Generated by Django 5.2.17 on 2026-08-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollment_unique_student_term_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='one_current_enrollment_per_student',
        ),
    ]
