# Generated by Django 5.2.17 on 2026-08-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_enrollment_one_current_enrollment_per_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
    ]
