# Generated by Django 5.2.17 on 2026-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_schoolevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
