# Generated by Django 5.2.17 on 2026-09-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classsubject'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='parent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='parent_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='parent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='relationship',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('other', 'Other')], default='guardian', max_length=20),
        ),
    ]
