# Generated by Django 5.2.17 on 2026-09-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classsubject'),
        ('admissions', '0002_admissionapplication_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionapplication',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.academicyear'),
        ),
    ]
