# Generated by Django 5.2.17 on 2026-09-03 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classsubject'),
        ('admissions', '0003_alter_admissionapplication_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.term'),
            preserve_default=False,
        ),
    ]
