# Generated by Django 5.2.17 on 2026-09-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admissionapplication_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='claim_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
