# Generated by Django 5.2.17 on 2026-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_admissionapplication_claim_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_email_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='admission_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
