# Generated by Django 5.2.17 on 2026-09-21 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_admissionapplication_admission_email_attempts_and_more'),
        ('students', '0005_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_application', to='students.student'),
        ),
    ]
