# Generated by Django 5.2.17 on 2026-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_classteacherassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
