# Generated by Django 5.2.17 on 2026-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=60,
            ),
        ),
    ]