# Generated by Django 5.2.17 on 2026-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_schoolclass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
