# Generated by Django 5.2.17 on 2026-09-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_group',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
