# Generated by Django 5.2.17 on 2026-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_recipient_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='announcement_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
